name: Test Application

on:
  push:
    branches: ["main", "staging"]
  pull_request:
    branches: ["main", "staging"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    services:
      mongodb:
        image: mongo:6.0.3
        env:
          MONGO_INITDB_DATABASE: test
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install required poetry
        run: pip install poetry
      - name: Install required dependencies
        run: poetry install
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 src --count --exit-zero --statistics
      - name: Run tests
        run: poetry run pytest
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          ENVIRONMENT: test
          TESTING: 0
          DATABASE_NAME: test
          API_VERSION: v1
          DATABASE_DSN: mongodb://user:password@127.0.0.1:27017/?retryWrites=true&w=majority