name: Test Application

on:
  push:
    branches: ["main", "staging"]
  pull_request:
    branches: ["main", "staging"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    services:
      mongodb:
        image: mongo:6.0.3
        env:
          MONGO_INITDB_DATABASE: test
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install required poetry
        run: pip install poetry
      - name: Install required dependencies
        run: poetry install
      - name: Lint files
        run: |
          chmod u+x scripts/lint.sh
          poetry run scripts/lint.sh
      - name: Run tests
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          ENVIRONMENT: test
          TESTING: 0
          DATABASE_NAME: test
          API_VERSION: v1
          DATABASE_DSN: mongodb://user:password@127.0.0.1:27017/?retryWrites=true&w=majority
          ENEBA_BASE_URI: ${{ secrets.ENEBA_BASE_URI }}
          ENEBA_CLIENT_ID: ${{ secrets.ENEBA_CLIENT_ID }}
          ENEBA_GRANT_TYPE: ${{ secrets.ENEBA_GRANT_TYPE }}
          ENEBA_ID: ${{ secrets.ENEBA_ID }}
          ENEBA_SECRET: ${{ secrets.ENEBA_SECRET }}
        run: |
          chmod u+x scripts/test.sh
          poetry run scripts/test.sh